# Site settings
title: Muhamad Faroek
description: Cloud Portofolio
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Varoek.github.io" # Your GitHub Pages URL (replace with your actual username)

# User settings
username: Muhamad Faroek
user_description:  AWS Cloud Practitioner certified with 10+ years of IT infrastructure experience. I help businesses move to the cloud by deploying WordPress, Odoo, and other web apps on AWS EC2.
baseurl: "" # leave this empty
user_title: Cloud & DevOps Enthusiast
email: mvaroek@gmail.com
# twitter_username: lorem_ipsum
instagram_username: varoek.muhamad
facebook_username: 
linkedin_username: https://www.linkedin.com/public-profile/settings?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_self_edit_contact-info%3Bqmr9I%2FYNQoeC2NO%2BfveE5w%3D%3D
github_username:  murraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

